version: '3.9'

services:
  postgres:
    container_name: postgres_flask_ligand
    image: postgres:10-alpine
    volumes:
      - ./docker/db-data/:/var/lib/postgresql/data/
      - ./docker/postgres-data/:/docker-entrypoint-initdb.d/
    env_file:
      - docker/env_files/integration.env
    ports:
      - '5432:5432'
    networks:
      - backend
    hostname: postgres_flask_ligand

  keycloak:
    container_name: keycloak_flask_ligand
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./docker/kc-data/:/opt/keycloak/data/import/
    env_file:
      - docker/env_files/integration.env
    depends_on:
      - postgres
    ports:
      - '8080:8080'
    networks:
      - backend
    command: start-dev --import-realm

networks:
  backend:
    name: backend
    driver: bridge
